### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rafucuk** [OmarElGabry/gunaydin#1]
> gunaydin@1.0.0 start /home/raufssen/Masaüstü/gunaydin
> node server.js

error: uncaughtException: OAuth2Strategy requires a clientID option date=Sun Sep 09 2018 20:47:53 GMT+0300 (+03), pid=8482, uid=1000, gid=1000, cwd=/home/raufssen/Masaüstü/gunaydin, execPath=/usr/bin/node, version=v8.10.0, argv=[/usr/bin/node, /home/raufssen/Masaüstü/gunaydin/server.js], rss=102256640, heapTotal=76230656, heapUsed=62517744, external=18878570, loadavg=[0.896484375, 1.029296875, 1.2353515625], uptime=5355
TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/home/raufssen/Masaüstü/gunaydin/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy (/home/raufssen/Masaüstü/gunaydin/node_modules/passport-facebook/lib/strategy.js:54:18)
    at /home/raufssen/Masaüstü/gunaydin/app/core/auth.js:65:15
    at Object.<anonymous> (/home/raufssen/Masaüstü/gunaydin/app/core/auth.js:69:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/raufssen/Masaüstü/gunaydin/server.js:10:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

npm ERR! Linux 4.15.0-33-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! gunaydin@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gunaydin@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gunaydin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gunaydin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gunaydin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/raufssen/Masaüstü/gunaydin/npm-debug.log

**Comment by OmarElgabry** [comment]
I believe you need to update the config file. You need to enter the client ID and secret for Facebook and Twitter to be able to login. If you don't, just comment out the auth code.
